config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end

  root 'pages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  def update_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes
  has_many :comments
  belongs_to :user, class_name: 'User'
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }
  def update_posts_counter
    user.update(posts_counter: user.posts.count)
  end

  def last_five_comment
    comments.includes(:post).order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'user_id'
  has_many :likes, foreign_key: 'user_id'
  has_many :comments, foreign_key: 'user_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0, only_integer: true }

  def three_most_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def show
    @comment = Comment.find(params[:user_id])
    @user = User.find(params[:user_id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = params[:user_id]
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to user_post_path(@comment.user_id, @comment.post_id)
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit!
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new
  end

  def create
    @like = Like.new(like_params)
    @like.user_id = params[:user_id]
    @like.post_id = params[:post_id]
    if @like.save
      redirect_to user_post_path(@like.user_id, @like.post_id)
    else
      render :new
    end
  end

  private

  def like_params
    params.require(:like).permit!
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show edit update destroy]

  def index
    @posts = Post.where(user_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def show
    @post = Post.find_by(id: params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.new(post_params)
    @post.user_id = @user.id
    if @post.save
      redirect_to user_posts_path(@user)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit!
  end

  def find_post
    @user = User.find(params[:user_id])

    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: %i[show edit update destroy]

  def index
    @users = User.all.order('created_at DESC')
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end

  def new
    @user = User.all
    @user = User.new
    @post = Post.new
  end

  def find_user
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
  <div id="<%= dom_id comment %>" class="comment-display">
  <p><strong><%= @user.name %>:</strong> <%= comment.text %> </p>
  </div>

app/views/comments/_form.html.erb
<%= form_with model: [@user, @post, @comment] do |form| %>

  <div>
    <%= form.label :user_id, "User ID:" %>
    <%= form.number_field :user_id, label: false %>
  </div>

  <div>
    <%= form.label :post_id, "Post ID:" %>
    <%= form.text_field :post_id, label: false %>
  </div>

  <div>
    <%= form.label :text, "Comment:" %>
    <%= form.text_area :text, label: false %>
  </div>

  <div>
    <%= form.submit "Add Comment" %>
  </div>
<% end %>

app/views/comments/new.html.erb
<div class="new-comment"> 
<%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>


    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/_form.html.erb
 <%= form_with model: [@user, @post, @like] do |form| %>
    <%= form.hidden_field :user_id, value: @user.id %>
    <%= form.hidden_field :post_id, value: @post.id %>
    <%= form.submit "Add like" %>
<% end %>

app/views/likes/new.html.erb
<%= render 'form' %>

app/views/pages/index.html.erb
<h2> database setup</h2>

     
<ul>

  <%= link_to "Sign Up" ,new_user_registration_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <h3>  <%= link_to  "Show all Authors" ,users_path %></h3>

         <li >
<%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-sm" %>
 </li>
<% else  %>
       <li > 
        <%= link_to "Log in" ,new_user_session_path   %>
 </li>


<% end %>

</ul>

app/views/posts/_form.html.erb
<%= form_with model: [@user, @post] do |form| %>

  <div>
    <%= form.label :user_id, "User ID:" %>
    <%= form.number_field :user_id, label: false %>
  </div>

  <div>
    <%= form.label :title, "Post Title:" %>
    <%= form.text_field :title, label: false %>
  </div>

  <div>
    <%= form.label :text, "Post Content:" %>
    <%= form.text_field :text, label: false %>
  </div>

  <div>
    <%= form.label :comments_counter %>
    <%= form.number_field :comments_counter, :value => 0 %>
  </div>

  <div>
    <%= form.label :likes_counter %>
    <%= form.number_field :likes_counter, :value => 0 %>
  </div>
    <%= form.submit "Add Post" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h4>index in  posts</h4>
<h3>  <%= link_to  "Home" ,root_path() %></h3>
<div class="users" >
  <div class="user_data" >
<div>
<h2> <%= @user.name %> </h2> 


    <h2>Posts counter <%= @user.posts_counter %> </h2>  
    </div>
     <img class="photo" src="https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"/>
</div>
   

  <% @posts.each do |post| %>
  <div class="user" >
  <h2> <%= post.text%> </h2> 
  <%= link_to "show", user_post_path(post.user_id,post.id) %>

  <h5> User Id: <%= post.user_id%> </h5> 
    <h5> Likes number <%= post.likes_counter%> </h5> 
    <h3>  <%= link_to  "View Post" ,user_post_path(@user.id,post.id) %></h3>
    </div>
      <div class="user_comments" >
  </div>
     <div class="comment-container">
     <% post.last_five_comment.each do |comment| %>
     <p><%= comment.user.name %>: <%= comment.text %></p>
        <% end %>
            </div>
  <% end %>
      <h3>  <%= link_to  "New post" ,new_user_post_path(@user.id) %></h3>

</div>

app/views/posts/new.html.erb
<div class="create-new-post">
<h2> Create A Post </h2>
<div class="post-form"> <%= render "form" %> </div>
</div>

app/views/posts/show.html.erb
<h4>Show in posts</h4>
<h3>  <%= link_to  "Home" ,root_path %></h3>
<div class="users" >

<h5>I love rock</h5>
<div >
  <h2>Post by: <%= @user.name%> </h2> 

 
  <h2> <%= @post.text%> </h2> 
    <h2> Comments <%= @post.comments_counter%> </h2> 
  <h2> Likes <%= @post.likes_counter%> </h2> 
 
</div>
      <h3>  <%= link_to  "New comment" ,new_user_post_comment_path(@user.id,@post.id) %></h3>
      <h3>  <%= link_to  "Like Post" ,new_user_post_like_path(@user.id,@post.id) %></h3>

</div>
<% @post.comments.each do |comment| %>
      <p><%= comment.user.name %>:     <%= comment.text %></p>
<% end %>

app/views/users/_author.html.erb
<div >
<h2> <%= user.name%> </h2> 
  
  
</div>

app/views/users/_form.html.erb
<%= form_with model: [@user] do |form| %>

  <div>
    <%= form.label :user_id, "User ID:" %>
    <%= form.number_field :user_id, label: false %>
  </div>

  <div>
    <%= form.label :title, "Post Title:" %>
    <%= form.text_field :title, label: false %>
  </div>

  <div>
    <%= form.label :text, "Post Content:" %>
    <%= form.text_field :text, label: false %>
  </div>

  <div>
    <%= form.label :comments_counter %>
    <%= form.number_field :comments_counter, :value => 0 %>
  </div>

  <div>
    <%= form.label :likes_counter %>
    <%= form.number_field :likes_counter, :value => 0 %>
  </div>
    <%= form.submit "Add Post" %>
  </div>
<% end %>

app/views/users/index.html.erb
<h4>index in  users</h4>
<h3>  <%= link_to  "Home" ,root_path %></h3>
<div class="users" >

  <% @users.each do |user| %>
  <div class="user" >
    <div class="user_data" >

  <h2> <%= user.name%> </h2> 
   <img class="photo" src="https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"/>
</div>
  
  <h2> Number of posts <%= user.posts_counter%> </h2> 
    <%= link_to "More details", user_path(user.id) %>
</div>
  <% end %>
  
</div>

app/views/users/new.html.erb
<div class="create-new-post">
<h2> Create A Post for a user </h2>
<div class="post-form"> <%= render "form" %> </div>
</div>

app/views/users/show.html.erb
<h4>show in users </h4>
<h3>  <%= link_to  "Home" ,root_path %></h3>
<div class="users" >
    <div class="user_data" >

<div>
<h5><%= @user.name%></h5> <h5>Posts Number:<%= @user.posts_counter%></h5>
</div>
<img src="https://images.unsplash.com/photo-1508921912186-1d1a45ebb3c1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80"/>
   
</div>


<div class="user" >
<h5>Bio</h5>
<h5><%= @user.bio%></h5>
</div>
 <% @posts.each do |post| %>
<div class="user" >
<h5> Post#<%= post.id%></h5>
<h5><%= post.text%></h5>
<h5> Comments:<%= post.comments_counter%></h5>
<h5> Likes:<%= post.likes_counter%></h5>

</div>
<% end %>
<h3>  <%= link_to  "Show all posts" ,user_posts_path(@user.id) %></h3>



</div>